SELECT * FROM estado

SELECT *FROM CIDADE

INSERT INTO ESTADO VALUES ('SP', 'São Paulo');

INSERT INTO CIDADE VALUES ('1','VOTORANTIN','SP');

INSERT INTO CIDADE (Codcidade, Nomecidade, Cdestado)
Values ('2','sorocaba', 'sp');

SELECT *FROM ESTADO

SELECT *FROM CIDADE

INSERT INTO CIDADE (Codcidade, Nomecidade, Cdestado)
Values ('3','itu','nn');

INSERT INTO CIDADE (Codcidade, Nomecidade, Cdestado)
Values ('4','Itapira', 'NN');

INSERT INTO ESTADO
VALUES
('NN','NÃO CADASTRADO');

SELECT *FROM CIDADE

UPDATE CIDADE
SET CDESTADO='SP'
WHERE CDESTADO='NN'

SELECT *FROM CIDADE

DELETE FROM CIDADE
WHERE NOMECIDADE = 'ITAPIRA'

SELECT *FROM CIDADE

CREATE TABLE Tbl_Clientes(
codigo INT IDENTITY (1,1) PRIMARY KEY, 
NOME VARCHAR (100),
UF VARCHAR (2));

SELECT *FROM TBL_CLIENTES

INSERT INTO TBL_CLIENTES
(NOME, UF)
VALUES ('Nicholas', 'RS');

SELECT *FROM TBL_CLIENTES

INSERT INTO TBL_CLIENTES(NOME, UF)
VALUES ('Pedro','SP');

select *from tbl_clientes

INSERT INTO TBL_CLIENTES (NOME, UF)
VALUES ('SKYWALKER','SP'),
('BRUCE','SP');

SELECT *FROM Tbl_Clientes

DELETE FROM Tbl_Clientes
WHERE CODIGO = 2

SELECT *FROM Tbl_Clientes

#PARA VER O ULTIMO REGISTRO#

SELECT IDENT_CURRENT('TBL_CLIENTES') AS ULTIMO_REGISTRO;