-- ATIVIDADE 7 - NOME: MARCEL MONTEIRO BALDUINO --

-- ITEM 1
CREATE TABLE PROFESSORES (
ID INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR (50) NOT NULL,
DISCIPLINA VARCHAR (15) NOT NULL,
)
-- ITEM 2
INSERT INTO PROFESSORES (NOME, DISCIPLINA)
VALUES ('ANA OLIVEIRA','PORTUGUES')

SELECT *FROM PROFESSORES

-- ITEM 3

UPDATE PROFESSORES 
SET NOME='ANA SILVA'
WHERE NOME= 'ANA OLIVEIRA'

SELECT *FROM PROFESSORES

-- ITEM 4

INSERT INTO PROFESSORES (NOME, DISCIPLINA)
VALUES ('JONAS_SANTOS','MATEMATICA'),
('RAFAEL_RICARDO', 'BIOLOGIA'), ('PEDRO_HENRIQUE','METODOLOGIA'),
('MARIA RITA','LABORATORIO_1'),
('FABIO COSTA','ASFALTO_2'),
('PAULO COSTA','RESMAT_2'),
('TEREZA COSTA','LITERATURA_1'),
('PAULO DUARTE','MICROBIOLOGIA'),
('AMANDA CAMARGO','GEOLOGIA'),
('MARCELO FERRAZ','PONTES')

-- ITEM 5  (EXCLUIR O PROFESSOR COM ID 24)

DELETE FROM PROFESSORES
WHERE ID=24

-- ITEM 6 (CRIAR UMA TABELA CHAMADA 'TURMAS'...)

CREATE TABLE TURMAS (
ID INT PRIMARY KEY IDENTITY (1,1),
NOME VARCHAR(50),
PROFESSORRESPONSAVEL INT,
CONSTRAINT FK_Professor_Turma FOREIGN KEY (PROFESSORRESPONSAVEL) REFERENCES PROFESSORES(ID)
)

-- ITEM 7 (ADICIONAR NOVA TURMA COM NOME "9A" ...

INSERT INTO TURMAS ( NOME, PROFESSORRESPONSAVEL)
VALUES ('9A',1)
